INSERT INTO category(name) VALUES('American');
INSERT INTO category(name) VALUES('Italian');
INSERT INTO category(name) VALUES('Mexican');
INSERT INTO category(name) VALUES('Fast Food');
INSERT INTO unit_of_measure(type) VALUES('Teaspoon');
INSERT INTO unit_of_measure(type) VALUES('Tablespoon');
INSERT INTO unit_of_measure(type) VALUES('Cup');
INSERT INTO unit_of_measure(type) VALUES('Pint');
INSERT INTO unit_of_measure(type) VALUES('Dash');
INSERT INTO unit_of_measure(type) VALUES('Each');